export const strings = {
  tabs: {
    dashboard: 'Dashboard',
    scan: 'Scan',
    history: 'History',
  },
  dashboard: {
    title: 'Budget Overview',
    noBudgetSet: 'Set up your first budget to start tracking.',
    remaining: 'remaining',
    daysLeft: 'days left',
    spent: 'Spent',
    ofBudget: 'of',
    topItems: 'Top Spending Items',
    trend: 'Spending Trend',
    categories: 'By Category',
    overBudget: 'Over budget',
    setBudget: 'Set Budget',
    noReceipts: 'No receipts scanned yet. Scan your first receipt to see spending data.',
  },
  budgetSettings: {
    title: 'Budget Settings',
    overallBudget: 'Overall Monthly Budget',
    categoryBudgets: 'Category Budgets',
    alertThresholds: 'Alert Thresholds',
    startDate: 'Budget Start Date',
    dayOfMonth: 'Day of month',
    save: 'Save Budget',
    saving: 'Saving...',
    saved: 'Budget saved!',
    amountPlaceholder: '0.00',
  },
  scan: {
    title: 'Scan Receipt',
    cameraPermission: 'Camera access is needed to scan receipts.',
    grantPermission: 'Grant Permission',
    processing: 'Processing receipt...',
    notAReceipt: "This doesn't appear to be a receipt.",
    captureButton: 'Capture Receipt',
    retake: 'Retake',
    usePhoto: 'Use Photo',
    uploadFromLibrary: 'Upload from Library',
    blurWarning: 'Image appears blurry. Hold steady.',
    lowLightWarning: 'Low light detected. Move to brighter area.',
    qualityError: 'Image quality too low. Please retake.',
    positionReceipt: 'Position receipt within the frame',
  },
  review: {
    title: 'Review Receipt',
    storeName: 'Store',
    date: 'Date',
    subtotal: 'Subtotal',
    tax: 'Tax',
    total: 'Total',
    items: 'Items',
    confirmAndSave: 'Confirm & Save',
    lowConfidence: 'Low confidence — please verify',
    noItems: 'No items extracted',
    editField: 'Tap to edit',
    category: 'Category',
    uncategorized: 'Uncategorized',
    saving: 'Saving...',
    saved: 'Receipt saved!',
    confirmDisabledReason: 'Store name and at least one item required',
    selectCategory: 'Select Category',
  },
  history: {
    title: 'Receipt History',
    empty: 'No receipts yet. Scan your first receipt to get started.',
    search: 'Search by store name...',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    allTime: 'All',
    items: 'items',
    pendingSync: 'Pending sync',
  },
  notifications: {
    title: 'Notification Settings',
    budgetAlerts: 'Budget Alerts',
    fiftyPercent: '50% threshold',
    eightyPercent: '80% threshold',
    hundredPercent: '100% threshold',
    weeklySummary: 'Weekly Summary',
    summaryEnabled: 'Enable weekly summary',
    summaryDay: 'Summary day',
    days: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
  },
  common: {
    confirm: 'Confirm',
    cancel: 'Cancel',
    retry: 'Retry',
    error: 'Something went wrong.',
  },
} as const;
